### ISSUE TITLE
libstdc++.so.6: version `x' not found 

### ISSUE THREAD

**Issue by JonasPertschy** [thgier/PotatoPresenter#1]
Hi Theresa,

Thank you for this project, I like to create presentations with LaTeX + beamer and you solved problems that concern me.

Trying to run the Potato Presenter app image under a vanilla Linux Mint installation fails due to missing dependencies. I cannot find any documented installation instructions. 

`root@user-virtual-machine:/home/user/Downloads# ./Potato_Presenter-v1.0.0-x86_64.AppImage 
./Potato_Presenter-v1.0.0-x86_64.AppImage: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./Potato_Presenter-v1.0.0-x86_64.AppImage)
./Potato_Presenter-v1.0.0-x86_64.AppImage: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./Potato_Presenter-v1.0.0-x86_64.AppImage)
`

The most recent libstdc++6 is installed in my VM:
`root@user-virtual-machine:/home/user/Downloads# apt-get install libstdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++6 is already the newest version (10.3.0-1ubuntu1~20.04).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
`

Could you please update the installation instructions after the rc3 talk? I really want to try out "PotatoPresenter".

**Comment by silmaril42** [comment]
I am facing exactly the same problem on Linux Mint 20.2 with current updates installed.

In the chat for your #rc3 talk, someone mentioned this link, which might be worth a look to get a more generic AppImage:
https://docs.appimage.org/reference/best-practices.html#binaries-compiled-on-old-enough-base-system

I'd try to build it myself, but I cannot find any build instructions in this project and a simple `cmake .` in the project folder throws errors :(

Would love to try this out, because the concept of the application really looks convincing :+1:

**Comment by qpd00z** [comment]
Same on Debian 11.2

**Comment by scummos** [comment]
For the record, the issue with the AppImage is that while it is compiled on an old Ubuntu as per the above link, it is compiled with a new gcc there, which requires a new libstdc++. :(

Effectively, this means you will need a very current system for the AppImage to work as of now, but that can certainly be fixed.

**Comment by thgier** [comment]
Hi, 
Thank you for your comments:)
I will build a new AppImage with the problem fixed (I think I can ship the needed version of libstdc++ in it) in the next couple of days and will test it more carefully.

**Comment by thgier** [comment]
This should be fixed in Release 1.0.1. Please tell me if not.
