### ISSUE TITLE
System update breaks latex support

### ISSUE THREAD

**Issue by ahormann** [thgier/PotatoPresenter#6]
I use Manjaro with KDE, everything was working fine until i made an system update today (including texlive 2021.61383-1 -> 2021.62659-1).
Now when i try to compile a slide with a latex formla (eg $x$) the terminal prints
latex exit code  "Unbekannter Fehler"
and the formula does not get displayed.
Restarting the computer, reinstalling the potato presenter and downgrading some of the texlive packets did not help.
Compiling latex-pdfs with pdflatex does still work.

**Comment by thgier** [comment]
The dvisvgm that the formula conversion uses is broken in the new update. I report this to the arch bug tracker:
https://bugs.archlinux.org/task/74480

**Comment by ahormann** [comment]
Great, that you tracked it down!

**Comment by thgier** [comment]
With the help of the maintainer of dvisvgm I figured out that the problem is due to the new Ghostscript version. With version 9.55.0 it should work. Alternatively, there is a Patch for dvisvgm that is not now released:
https://github.com/mgieseki/dvisvgm/commit/653220ebb129bc118329397b1ad2b58847d91c21

**Comment by ahormann** [comment]
That fixed it!
Thank you!
